### ISSUE TITLE
`JSONDecoder` should adopt `CombineX.TopLevelDecoder` directly.

### ISSUE THREAD

**Issue by ddddxxx** [cx-org/CXFoundation#1]
Currently we need to use `JSONDecoder().cx.decoder`, thats awkward and unintuitive.

I'd create pr with your permission.

**Comment by luoxiu** [comment]
You are right. `JSONDecoder` is naturally able to conform to `CombineX.TopLevelDecoder` without adding new types/methods, and `JSONEncoder`, `PropertyListDecoder/Encoder` are the same.

I'm also struggling, you should know the naming conflicts problem of `Scheduler`. People need to use `q.cx.scheduler` to avoid that. I know this looks ugly(very very very ugly), but at least they have a uniform specification. 😖

Do you have any good ideas? We can discuss! Big breaking changes are also acceptable!

**Comment by ddddxxx** [comment]
I think current rule is fine (except `TopLevelEncoder/Decoder` stuff), using `.cx` as namespace, like `.rx` for RxSwift and `.snp` for SnapKit, is uniform and predictable.

The rule is simple: for properties and functions `Combine` directly extends the `Foundation` type, put them under `.cx` namespace.

`JSONDecoder` effectively violate the rule. We don't need `JSONDecoder().decoder` in `Combine`. the `decode` property is contrived. (I can even accept `JSONDecoder().cx`)

I'd suggest another rule: for `Foundation` types directly adopts `Combine`'s protocol, they just adopt `CombineX`'s protocol accordingly.

**Comment by luoxiu** [comment]
Fixed in [0.0.1-beta.5](https://github.com/cx-org/CXFoundation/releases/tag/0.0.1-beta.5).

I will update readme later. 

Thanks!
