### ISSUE TITLE
Cannot resolve dependencies anymore using SPM

### ISSUE THREAD

**Issue by jakobmygind** [cx-org/CXFoundation#7]
![image](https://user-images.githubusercontent.com/8362263/67008499-e31ebf00-f0e9-11e9-993c-7232bec0b74d.png)

I am trying to use master

**Comment by luoxiu** [comment]
Hi @jakobmygind , CX is under actively refactoring, CXFoundation was already moved to [CombineX](https://github.com/cx-org/CombineX), please try that package directly~
